### ISSUE TITLE
CoordSet.to/asChunkOffset() method probably doesn't work like it should

### ISSUE THREAD

**Issue by NPException42** [Jezza/OmnisCore#6]
I guess that the offset method is supposed to deliver a value of 0-15 for each coordinate part, so it then points to the spot of the block relative to the chunk it is in, right?

If that's the case, then it is not working like it should. Once the source coordinates get into the negative range, the offset is wrong. Try -7 % 16 for yourself. ;)

And it caused this in Dimensional Pockets for example:

![c8e5e7e5f2 1](https://cloud.githubusercontent.com/assets/6052580/6003600/302844fc-aafd-11e4-9839-008670dee9b7.jpg)

I have made a workaround in DP for now, but you should probably fix that for the next version of Omnis Core. ^^

**Comment by Jezza** [comment]
Fixed.
