### ISSUE TITLE
Minecraft crashes on launch b/c of OmnisCore

### ISSUE THREAD

**Issue by cdh0127** [Jezza/OmnisCore#7]
Time: 6/3/15 10:57 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.ClassNotFoundException: me.jezza.oc.OmnisCore
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:502)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:204)
	at com.creativemd.minecraftloader.ClientHelper.startGame(ClientHelper.java:260)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: me.jezza.oc.OmnisCore
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at cpw.mods.fml.common.ModClassLoader.loadClass(ModClassLoader.java:58)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:249)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:420)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.creativemd.minecraftloader.MinecraftDummyContainer.callMethod(MinecraftDummyContainer.java:209)
	at com.creativemd.minecraftloader.MinecraftDummyContainer.onModEvent(MinecraftDummyContainer.java:201)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:492)
	... 11 more
Caused by: java.lang.UnsupportedClassVersionError: me/jezza/oc/OmnisCore : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 43 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Mac OS X (x86_64) version 10.10.4
	Java Version: 1.6.0_65, Apple Inc.
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
	Memory: 167386760 bytes (159 MB) / 481333248 bytes (459 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 119 mods loaded, 119 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed
	FML{7.10.85.1291} [Forge Mod Loader] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed
	Forge{10.13.2.1291} [Minecraft Forge] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed
	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed
	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) Unloaded->Constructed
	minecraftloader{0.1} [MinecraftLoader] (minecraft.jar) Unloaded->Constructed
	MobiusCore{1.2.3} [MobiusCore] (minecraft.jar) Unloaded->Constructed
	NotEnoughItems{1.0.3.73} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.3.73-universal.jar) Unloaded->Constructed
	OpenComputers|Core{1.0.0} [OpenComputers (Core)] (minecraft.jar) Unloaded->Constructed
	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) Unloaded->Constructed
	OpenModsCore{0.6} [OpenModsCore] (minecraft.jar) Unloaded->Constructed
	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) Unloaded->Constructed
	debug{1.0} [debug] (denseores-1.5.jar) Unloaded->Constructed
	AWWayofTime{v1.3.0Beta} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.0Beta-6.jar) Unloaded->Constructed
	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed
	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) Unloaded->Constructed
	Botania{r1.3-143} [Botania] (Botania r1.3-143.jar) Unloaded->Constructed
	CoFHCore{1.7.10R3.0.2} [CoFH Core] (CoFHCore-[1.7.10]3.0.2-262.jar) Unloaded->Constructed
	BuildCraft|Core{6.2.6} [BuildCraft] (buildcraft-6.2.6.jar) Unloaded->Constructed
	BuildCraft|Transport{6.2.6} [BC Transport] (buildcraft-6.2.6.jar) Unloaded->Constructed
	BuildCraft|Silicon{6.2.6} [BC Silicon] (buildcraft-6.2.6.jar) Unloaded->Constructed
	BuildCraft|Builders{6.2.6} [BC Builders] (buildcraft-6.2.6.jar) Unloaded->Constructed
	BuildCraft|Energy{6.2.6} [BC Energy] (buildcraft-6.2.6.jar) Unloaded->Constructed
	BuildCraft|Factory{6.2.6} [BC Factory] (buildcraft-6.2.6.jar) Unloaded->Constructed
	ChickenChunks{1.3.4.14} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.14-universal.jar) Unloaded->Constructed
	IC2{2.2.648-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.648-experimental.jar) Unloaded->Constructed
	CompactSolars{4.4.37.314} [Compact Solar Arrays] (CompactSolars-1.7.10-4.4.37.314-universal.jar) Unloaded->Constructed
	customnpcs{1.7.10d} [CustomNpcs] (CustomNPCs_1.7.10d.jar) Unloaded->Constructed
	OmnisCore{0.1.0} [Omnis Core] (OmnisCore-1.7.10 - 0.0.6-universal.jar) Unloaded->Errored
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed
	MineFactoryReloaded{1.7.10R2.8.0RC7} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed
	ThermalFoundation{1.7.10R1.0.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0-81.jar) Unloaded->Constructed
	ThermalExpansion{1.7.10R4.0.1} [Thermal Expansion] (ThermalExpansion-4.0.1-182.jar) Unloaded->Constructed
	Waila{1.5.6a} [Waila] (Waila-1.5.6a_1.7.10.jar) Unloaded->Constructed
	TConstruct{1.7.10-1.8.3.build919} [Tinkers' Construct] (TConstruct-1.7.10-1.8.3b.jar) Unloaded->Constructed
	dimensionalPockets{0.10.4} [Dimensional Pockets] (dimensionalPockets-0.10.4.jar) Unloaded->Errored
	EnderIO{1.7.10-2.2.7.325} [Ender IO] (EnderIO-1.7.10-2.2.7.325.jar) Unloaded->Constructed
	EnderStorage{1.4.5.26} [EnderStorage] (EnderStorage-1.7.10-1.4.5.26-universal.jar) Unloaded->Constructed
	ForgeMultipart{1.1.1.320} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed
	ExtraUtilities{1.2.2} [Extra Utilities] (extrautils-1.2.2.jar) Unloaded->Constructed
	factorization.notify{1.0} [Factorization Notification System] (Factorization-1.7.10-0.8.88.1.jar) Unloaded->Constructed
	factorization{1.7.10-0.8.88.1} [Factorization] (Factorization-1.7.10-0.8.88.1.jar) Unloaded->Constructed
	factorization.misc{1.7.10-0.8.88.1} [Factorization Miscellaneous Nonsense] (Factorization-1.7.10-0.8.88.1.jar) Unloaded->Constructed
	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer-2.5-1.7.10-164.jar) Unloaded->Constructed
	ForbiddenMagic{1.7.10-0.561} [Forbidden Magic] (forbidden magic-0.561.jar) Unloaded->Constructed
	Forestry{3.3.0.6} [Forestry for Minecraft] (forestry_1.7.10-3.3.0.6.jar) Unloaded->Constructed
	GalacticraftCore{3.0.11} [Galacticraft Core] (GalacticraftCore-1.7-3.0.11.333.jar) Unloaded->Constructed
	GalacticraftMars{3.0.11} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.11.333.jar) Unloaded->Constructed
	IC2NuclearControl{2.2.5a-GoingForTheKill} [Nuclear Control 2] (IC2NuclearControl-2.2.5a-GoingForTheKill.jar) Unloaded->Constructed
	iChunUtil{4.0.0} [iChunUtil] (iChunUtil-4.0.0.jar) Unloaded->Constructed
	InfernalMobs{1.6.0} [Infernal Mobs] (InfernalMobs-1.7.10.jar) Unloaded->Constructed
	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) Unloaded->Constructed
	IronChest{6.0.60.741} [Iron Chest] (ironchest-1.7.10-6.0.60.741-universal.jar) Unloaded->Constructed
	MetallurgyCore{4.0.4} [Metallurgy Core] (metallurgycore-4.0.4.18.jar) Unloaded->Constructed
	Metallurgy{4.0.8} [Metallurgy 4] (metallurgy-4.0.8.97.jar) Unloaded->Constructed
	minechem{5.0.5.394} [Minechem] (Minechem-5.0.5.394.jar) Unloaded->Constructed
	MineChess{1.3.8} [MineChess] (MineChess-1.3.9.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0RC7} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatAtum{1.7.10R2.8.0RC7} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0RC7} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0RC7} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0RC7} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0RC7} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatForestry{1.7.10R2.8.0RC7} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0RC7} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatIC2{1.7.10R2.8.0RC7} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0RC7} [MFR Compat: Mystcraft] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed
	MrTJPCoreMod{1.0.5.11} [MrTJPCore] (MrTJPCore-1.7.10-1.0.5.11-universal.jar) Unloaded->Constructed
	ProjRed|Core{4.5.14.66} [ProjectRed] (projectred-4.5.14.66.base.jar) Unloaded->Constructed
	ProjRed|Exploration{4.5.14.66} [ProjectRed-Exploration] (projectred-4.5.14.66.world.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0RC7} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0RC7} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatRP2{1.7.10R2.8.0RC7} [MFR Compat: RP2] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0RC7} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0RC7} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0RC7} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0RC7} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0RC7} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0RC7} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Constructed
	numina{0.4.0.100} [Numina] (Numina-0.4.0.100.jar) Unloaded->Constructed
	powersuits{0.11.0.176} [MachineMuse's Modular Powersuits] (ModularPowersuits-0.11.0.176.jar) Unloaded->Constructed
	MorePlanet{1.2.8} [More Planets] (More-Planets-1.7.10-1.2.8.jar) Unloaded->Constructed
	cfm{3.4.7} [ß9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10).jar) Unloaded->Constructed
	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1.jar) Unloaded->Constructed
	NEIAddons{1.12.3.11} [NEI Addons] (neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed
	NEIAddons|Botany{1.12.3.11} [NEI Addons: Botany] (neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed
	NEIAddons|Forestry{1.12.3.11} [NEI Addons: Forestry] (neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed
	NEIAddons|CraftingTables{1.12.3.11} [NEI Addons: Crafting Tables] (neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed
	NEIAddons|ExNihilo{1.12.3.11} [NEI Addons: Ex Nihilo] (neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed
	neiintegration{1.0.5} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.5.jar) Unloaded->Constructed
	NotEnoughCodecs{0.3} [NotEnoughCodecs] (NotEnoughCodecs-1.7.10-0.3-snapshot-11.jar) Unloaded->Constructed
	NuclearCraft{0.0.0.9b} [NuclearCraft] (NuclearCraft-0.0.1.0.jar) Unloaded->Constructed
	OpenMods{0.6} [OpenMods] (OpenModsLib-1.7.10-0.6-snapshot-268.jar) Unloaded->Constructed
	OpenBlocks{1.3} [OpenBlocks] (OpenBlocks-1.7.10-1.3-snapshot-513.jar) Unloaded->Constructed
	ProjRed|Transmission{4.5.14.66} [ProjectRed-Transmission] (projectred-4.5.14.66.integration.jar) Unloaded->Constructed
	OpenComputers{1.4.6.30} [OpenComputers] (OpenComputers-MC1.7.10-1.4.6.30-universal.jar) Unloaded->Constructed
	harvestcraft{1.7.10d} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10d.jar) Unloaded->Constructed
	PneumaticCraft{1.4.3-40} [PneumaticCraft] (PneumaticCraft-1.7.10-1.4.3-40-universal.jar) Unloaded->Constructed
	ProjRed|Transportation{4.5.14.66} [ProjectRed-Transportation] (projectred-4.5.14.66.mechanical.jar) Unloaded->Constructed
	ProjRed|Compatibility{4.5.14.66} [ProjectRed-Compatibility] (projectred-4.5.14.66.compat.jar) Unloaded->Constructed
	ProjRed|Integration{4.5.14.66} [ProjectRed-Integration] (projectred-4.5.14.66.integration.jar) Unloaded->Constructed
	ProjRed|Illumination{4.5.14.66} [ProjectRed-Illumination] (projectred-4.5.14.66.lighting.jar) Unloaded->Constructed
	ProjRed|Expansion{4.5.14.66} [ProjectRed-Expansion] (projectred-4.5.14.66.mechanical.jar) Unloaded->Constructed
	redgear_core{2.2.0} [Red Gear Core] (RedGearCore-1.7.10-2.2.0.jar) Unloaded->Constructed
	runicdungeons{0.9.7} [Runic Dungeons] (runicdungeons-0.9.7.jar) Unloaded->Constructed
	securitycraft{v1.6.1} [SecurityCraft] (securitycraft-1.6.1.jar) Unloaded->Constructed
	supercraftingframe{1.7.10.3} [Super Crafting Frame] (supercraftingframe-1.7.10.3.jar) Unloaded->Constructed
	ThaumicExploration{0.6.0} [Thaumic Exploration] (ThaumicExploration-1.7.10-1.1-29.jar) Unloaded->Constructed
	ThermalDynamics{1.7.10R1.0.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.0.0-122.jar) Unloaded->Constructed
	TiCTooltips{1.2.3} [TiC Tooltips] (tictooltips-1.2.3.jar) Unloaded->Constructed
	TMechworks{1.7.10-86.e500b88} [Tinkers' Mechworks] (tmechworks-0.2.10.jar) Unloaded->Constructed
	ttCore{MC1.7.10-0.1.1-73} [ttCore] (ttcore-0.1.1.73.jar) Unloaded->Constructed
	WailaHarvestability{1.1.1} [Waila Harvestability] (wailaharvest-1.1.1.jar) Unloaded->Constructed
	wailaplugins{MC1.7.10-0.0.1-14} [WAILA Plugins] (WAILAPlugins-0.0.1-14.jar) Unloaded->Constructed
	witchery{0.20.6} [Witchery] (witchery-1.7.10-0.20.6.jar) Unloaded->Constructed
	ZombieInfection{1.2.0} [Zombie Infection] (zombieinfection-1.2.1.jar) Unloaded->Constructed
	McMultipart{1.1.1.320} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed
	denseores{1.0} [Dense Ores] (denseores-1.5.jar) Unloaded->Constructed
	ForgeMicroblock{1.1.1.320} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed
	OpenModsLib crash transformers: [gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED],[map_gen_fix:ENABLED],[movement_callback:FINISHED],[stencil_patches:FINISHED]
	CoFHCore: -[1.7.10]3.0.2-262
	Mantle Environment: Environment healthy.
	MineFactoryReloaded: -[1.7.10]2.8.0RC7-71
	ThermalFoundation: -[1.7.10]1.0.0-81
	ThermalExpansion: -[1.7.10]4.0.1-182
	TConstruct Environment: Environment healthy.
	ThermalDynamics: -[1.7.10]1.0.0-122

**Comment by Jezza** [comment]
It looks like a Java version error. 
Updating your java to java 7 will fix it. 
:)

**Comment by cdh0127** [comment]
I believe I am on 7 or 8….but I just my downgraded OmnisCore version.

**Comment by Jezza** [comment]
Oh, I assumed it was for use with Thaumic Pipes. 
Yeah. OC 0.0.6 currently doesn't work with Dimensional Pockets. 
Sorry.

**Comment by cdh0127** [comment]
That’s quite alright :)
I’m just happy after a week of troubleshooting errors with various mods and versions, that it finally runs :D

**Comment by Jezza** [comment]
Sorry about that... 
If it makes you feel any better, I haven't had my computer for 2ish months... :/

**Comment by cdh0127** [comment]
Oh no no it wasn’t purely because of Omnis Core! I had a variety of different mods conflicting with each other. 
And sorry to hear about that :/

**Comment by NPException42** [comment]
no, he doesn't have his PC because some idiot made him move to Germany.

2015-06-05 19:51 GMT+02:00 cdh0127 <notifications@github.com>:

> Oh no no it wasn’t purely because of Omnis Core! I had a variety of
> different mods conflicting with each other.
> And sorry to hear about that :/

**Comment by Jezza** [comment]
Well, that least that's slightly pleasant to hear. 
I'm glad you finally got it all working!

**Comment by Jezza** [comment]
One day my computer and I will reunite... 
That stupid derp.... Making an Aussie move to Germany....

**Comment by NPException42** [comment]
Yeah. You should punch that guy next monday :D

**Comment by Jezza** [comment]
Oh, he's had it coming for a while. 
:D
